
#
# Site settings
#
title: All About Cheetahs!
email: dmuth@dmuth.org
description: > # this means to ignore newlines until "baseurl:"
  Everything you'd ever want to know about cheetahs. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.all-about-cheetahs.com" # the base hostname & protocol for your site
twitter_username: dmuth
github_username:  dmuth

#
# Build settings
#
markdown: kramdown

sass:
  style: compressed

